### ISSUE TITLE
[✅ASSIGNED] Code Preview Feature

### ISSUE THREAD

**Issue by app-generator** [app-generator/rocket-builder#11]
> `STATUS`:  **ASSIGNED** to @umarali 

---

### Context 

The codebase needs to allow users to preview the current design.

Here are the changes:

- Add a new button in the navigation bar
- when the user clicks,t the current design can be previewed in a modal window 

For Questions, feel free to ask here. 

TY!

**Comment by app-generator** [comment]
Validated. Closing.

**Comment by whitetiger1002** [comment]
Is it still open?

**Comment by app-generator** [comment]
Hello @whitetiger1002 

This is done, but we will need help on other items. 
If you have the time, fork & build the project, just to accommodate the codebase. 

TY!

**Comment by app-generator** [comment]
Yes, we are looking for maintainers. 
For each new evolution, will be a new issue open, and `devs` can apply.

Through this, we will accelerate the development.

**Comment by whitetiger1002** [comment]
As a full-stack developer, I am available to work on your prjoect.
How much can I get paid?

**Comment by app-generator** [comment]
Hello @whitetiger1002 

Each new issue will have the budget listed.

**Comment by whitetiger1002** [comment]
Well, my email is eric.elite1002@gmail.com
May I have your email address?

**Comment by app-generator** [comment]
Hello @VladyslavZaporozhets, @whitetiger1002 

Thank you both for the follow-up. 

This feature is already assigned to @umarali. In order to contribute, please monitor unassigned ISSUES and submit a request. 

TY!

**Comment by app-generator** [comment]
@umarali this feature has an improvement request #19 

Please take a look. TY!

**Comment by EliasSbehat** [comment]
You need to do Code Preview Feature?
If yes, I can do this

**Comment by EliasSbehat** [comment]
Hi there.
I can do this task.
Can you please assign me this task?
Thanks!
Elias

**Comment by app-generator** [comment]
@umarali looks better in the latest version
If possible, please set the viewport in the center of the modal.

Currently, is `LEFT-aligned`

Please take a look.
TY!

![image](https://github.com/app-generator/rocket-builder/assets/51070104/5d2e08dd-ba53-4a03-8d3d-d29d18c333fb)

**Comment by app-generator** [comment]
Perfect @umarali 

I let you know when the code needs to be migrated on HEAD. 
I'm pretty sure now we have conflicts. 

TY!
