### ISSUE TITLE
[✅ASSIGNED] Preview Improvements

### ISSUE THREAD

**Issue by app-generator** [app-generator/rocket-builder#19]
> `STATUS`:  **ASSIGNED** to @umarali 

---

### Context 

The current layout of the preview might be improved by the following changes: 

- Center the control buttons
- adjust the width of the modal based on the selected device 
  - if this is not possible, center the viewport (now stands aside) 
- Remove the borders injected by the mouse over events 

A possible solution might be:

- Deep copy the content of the Dropzone
- cleanUp the classes injected by the mouseOver events for components highlighting
- inject the HTML code in the viewport 

@umarali please take a look. 
TY! 

--- 

![image](https://github.com/app-generator/rocket-builder/assets/51070104/90e980b8-1260-4272-8458-dad98ba9965f)

**Comment by app-generator** [comment]
NOTE: Code needs to be committed under `preview-improvement` branch

https://github.com/app-generator/rocket-builder/tree/preview-improvement

@umarali, once the fix is done, leave it on the branch for validation 

TY!

**Comment by umarali** [comment]
@app-generator got it!

**Comment by umarali** [comment]
> @app-generator pushed minor updates and created PR. Mouse events currently don't work for action items besides links.

You'd like to take care of mouse events as part of this very issue or in a separate one?

**Comment by app-generator** [comment]
Validated. Closing.
