### ISSUE TITLE
[✅ASSIGNED] Download Option

### ISSUE THREAD

**Issue by app-generator** [app-generator/rocket-builder#20]
> `STATUS`:  **ASSIGNED** to @EliasSbehat, Budget **$100** (paid via UpWork)

---

### Context 

The codebase needs to be improved with a download option (currently only PREVIEW is available). 

The download needs to be a ZIP archive with the following: 

```bash
<site.zip>
   |-- index.html 
   |-- assets/
          |-- CSS 
          |-- js 
          |-- images   
```

NOTE: The project doesn't have a backend (yet).

**Comment by EliasSbehat** [comment]
I can do this working.

Thank you!

Elias

**Comment by app-generator** [comment]
Ty @EliasSbehat. Let's go!

**Comment by EliasSbehat** [comment]
Thanks

**Comment by app-generator** [comment]
The code needs to be committed on `feature-download` branch

https://github.com/app-generator/rocket-builder/tree/feature-download

TY @EliasSbehat

**Comment by EliasSbehat** [comment]
Done

**Comment by EliasSbehat** [comment]
I am waiting the review.

**Comment by app-generator** [comment]
Hello @EliasSbehat 

Ty for your work. 

The download needs to provide the page without the border. basically, what the user edits INSIDE the Dropzone.

The rest is all good. 

TY! 

--- 

![image](https://github.com/app-generator/rocket-builder/assets/51070104/b176e58d-457f-4c59-b2d0-2a4a1bdeafcd)

**Comment by EliasSbehat** [comment]
ok

**Comment by EliasSbehat** [comment]
I changed it
Please check

**Comment by EliasSbehat** [comment]
![image](https://github.com/app-generator/rocket-builder/assets/131557776/647d9df1-b4ec-4c4c-8d8d-fa2177a1293f)

**Comment by EliasSbehat** [comment]
👍

**Comment by app-generator** [comment]
Validated. Closing.
