### ISSUE TITLE
[✅ASSIGNED] Component PROPS - Images URL

### ISSUE THREAD

**Issue by app-generator** [app-generator/rocket-builder#21]
> `STATUS`:  **ASSIGNED** to @topstar210 , Budget **$50** (paid via UpWork)

**NOTE** Feature Depends on #18 (Redux Integration & Refactoring)

---

### Context 

In the current version, the PROPS available for the current element are:
- text
- URLs 

The new evolution should empower the user to update the `IMG.src` property via an external LINK. 

For now, image uploads are not supported.

**Comment by EliasSbehat** [comment]
I will do this

Thank you!

Elias

**Comment by topstar210** [comment]
Hi, I think it's my job.
Very similar with my past job: changing href of a tag

**Comment by app-generator** [comment]
Hello @topstar210 

The component is available on the server. 

Please proceed with the task.
TY! 

![image](https://github.com/app-generator/rocket-builder/assets/51070104/d412c6b7-6c12-48c5-bde7-567a82fc5872)

**Comment by app-generator** [comment]
P.S. The code needs to be added on `props-img-url`

https://github.com/app-generator/rocket-builder/tree/props-img-url

TY!

**Comment by topstar210** [comment]
Done!

**Comment by app-generator** [comment]
Validated. Closing.
