### ISSUE TITLE
[👉UNASSIGNED] Component Styling - Classes, Custom CSS

### ISSUE THREAD

**Issue by app-generator** [app-generator/rocket-builder#22]
> `STATUS`:  **UNASSIGNED**, Budget **$100** (paid via UpWork)

**NOTE** Feature Depends on #18 (Redux Integration & Refactoring)

---

### Context 

In the current version, the PROPS available for the current element are:
- text
- URLs 

The new evolution should empower the user to update the active element via:

- custom CSS
- Add / Remove CSS classes 

The classes are presented to the user as navPills and the changes will be automatically reflected on the target component.

**Comment by EliasSbehat** [comment]
Hi there!
I can do this task.
Looking forward to assign me.
Thanks
Elias

**Comment by topstar210** [comment]
I understood your requirement
I can do it
Thanks

**Comment by EliasSbehat** [comment]
Hi there!
This is available till?
If yes, I will do this task.
Thank you!
Elias

**Comment by app-generator** [comment]
Duplicated. CLosing.
