### ISSUE TITLE
[✅ASSIGNED] Delete & Reorder option

### ISSUE THREAD

**Issue by app-generator** [app-generator/rocket-builder#29]
> `STATUS`:  **ASSIGNED** to @EliasSbehat, , Budget **$50** (paid via UpWork)
---

### Context 

Root components (GRIDs or standalone) need to support the following:

- change order: UP, DOWN
- delete component 

<br />

### How it works:

- on mouse-over, the ROOT component needs to have:
  - UP, DOWN arrows to change the order 
- Delete Control
  - classic `x` control positioned on the top right corner of the component

**Comment by EliasSbehat** [comment]
ok

**Comment by app-generator** [comment]
Validated. Closing.
