### ISSUE TITLE
[✅ASSIGNED] Custom Style & CSS Classes

### ISSUE THREAD

**Issue by app-generator** [app-generator/rocket-builder#32]
> `STATUS`:  **ASSIGNED** to @EliasSbehat, , Budget **$50** (paid via UpWork)
---

### Context 

For each selectable element, the `PROPS` tab needs to provide a minimal UI for styling: 

-  Style (label)
  -  input where the current styling is injected and the user can edit  
- Classes
  - `input` for existing classes
  - pills for the existing classes that the user can dismiss (delete) 

@EliasSbehat please take a look.

TY! 
---

![image](https://github.com/app-generator/rocket-builder/assets/51070104/73f19c19-a7b3-4d13-a298-0a8d32f3723d)

**Comment by EliasSbehat** [comment]
Will do this soon

**Comment by EliasSbehat** [comment]
Done

**Comment by app-generator** [comment]
Validated. Closing.
