### ISSUE TITLE
[✅ASSIGNED] Page Globals - SEO, Externa CSS, External JS 

### ISSUE THREAD

**Issue by app-generator** [app-generator/rocket-builder#33]
> `STATUS`:  **ASSIGNED** to @EliasSbehat, , Budget **$50** (paid via UpWork)
---

### Context 

The current page needs to be customized regarding the Global Data:

- SEO
  - Title
  - description 
  - keywords
- External CSS
  - a single URL
- External JS
  - a single URL

@EliasSbehat please take a look.
TY! 

--- 

![image](https://github.com/app-generator/rocket-builder/assets/51070104/6f4fe728-c954-49d4-853f-151fe4cfdf72)

**Comment by EliasSbehat** [comment]
Will do

**Comment by app-generator** [comment]
Validated. Closing.
