### ISSUE TITLE
[✅ASSIGNED] Preview Works only for Index.html

### ISSUE THREAD

**Issue by app-generator** [app-generator/rocket-builder#43]
> `STATUS`:  **ASSIGNED** to @EliasSbehat, Budget **$25** (paid via UpWork)

---

### Context 

The `Preview` feature needs to be improved to work for the active page.
Currently, the index works only for `index.html` 

@EliasSbehat please take a look. 

TY!

**Comment by EliasSbehat** [comment]
Will do

**Comment by app-generator** [comment]
Validated. Closing.
