### ISSUE TITLE
[✅ASSIGNED] Clear Works only for index

### ISSUE THREAD

**Issue by app-generator** [app-generator/rocket-builder#44]
> `STATUS`:  **ASSIGNED** to @EliasSbehat, Budget **$25** (paid via UpWork)

---

### Context 

In the context of `multi-page` support, the `clear` handler needs to do the following: 

- would be nice to have confirmation from the user
  - via a modal
- Reset `index.html`
- Delete all pages (except index) 

In other words, the `clear` action needs to put the app in the initial state (first-time action for a user). 

@EliasSbehat please take a look.
TY!

**Comment by EliasSbehat** [comment]
Will do

**Comment by EliasSbehat** [comment]
Done

**Comment by app-generator** [comment]
Hello @EliasSbehat 

Here are the issues with the current implementation:

- components on the index are not deleted 
- the 2nd clear action, just hangs and the popup remains active even the user clicks on `OK`

Please take a look.
TY!

**Comment by EliasSbehat** [comment]
ok

**Comment by EliasSbehat** [comment]
Done

**Comment by EliasSbehat** [comment]
https://github.com/app-generator/rocket-builder/tree/fix-44

**Comment by app-generator** [comment]
testing .. ty

**Comment by app-generator** [comment]
Not validated. Here is the latest behavior.

Please take a look @EliasSbehat 

TY! 

![rocket-builder-clear-issue](https://github.com/app-generator/rocket-builder/assets/51070104/c6fd2a6f-1e59-4ef0-921e-e8a33677c4be)

**Comment by app-generator** [comment]
Validated. Closing.
