### ISSUE TITLE
[✅ASSIGNED] Persistence on Page Refresh works only for Index

### ISSUE THREAD

**Issue by app-generator** [app-generator/rocket-builder#47]
> `STATUS`:  **ASSIGNED** to @EliasSbehat, Budget **$25** (paid via UpWork)

---

### Context 

In the context of `multi-page` support, when the user reloads the page, the existing edits (all pages) need to be restored.
Currently, this works only for the `index.html`.

@EliasSbehat please take a look.
TY!

**Comment by EliasSbehat** [comment]
Will do

**Comment by EliasSbehat** [comment]
Done

**Comment by app-generator** [comment]
Validated. Closing. 
TY @EliasSbehat
