### ISSUE TITLE
[✅ASSIGNED] Multi-Page Preview - Enhancement

### ISSUE THREAD

**Issue by app-generator** [app-generator/rocket-builder#50]
> `STATUS`:  **ASSIGNED** to @EliasSbehat, Budget **$25** (paid via UpWork)

---

### Context 

In the current version, the preview works only for the current page. 
Would be nice to have a complete `PREVIEW` feature where the user can switch the pages in the same modal. 

@EliasSbehat please take a look. 

TY!

--- 

![image](https://github.com/app-generator/rocket-builder/assets/51070104/98d7af1f-7b49-4a41-97e2-cf24d1e45df1)

**Comment by EliasSbehat** [comment]
ok

**Comment by app-generator** [comment]
Validated. Closing.
