### ISSUE TITLE
[✅ASSIGNED] Page Name Update - Not persistent after update 

### ISSUE THREAD

**Issue by app-generator** [app-generator/rocket-builder#53]
> `STATUS`:  **ASSIGNED** to @EliasSbehat,, Budget **$25**, paid via UpW

---

### Context 

The user creates a new page and later updates the name. This is correctly managed in the editing tabs and PROPs panel

Issues: 

- the NEW page name is not persistent on page refresh
  - when the user hits the `F5` in the browser 
- this issue is visible also in the `Preview`
  - old name is used 

The solution is to update the name in all related contexts saved in the `localStorage`. 

@EliasSbehat please take a look.

TY!

**Comment by EliasSbehat** [comment]
Will do

**Comment by app-generator** [comment]
TY @EliasSbehat

**Comment by app-generator** [comment]
Validated. Closing.
TY @EliasSbehat
